/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacadastro.visao;

import static java.awt.SystemColor.info;
import javax.swing.JOptionPane;
import sistemacadastro.arquivos.LerUsuario;
import sistemacadastro.arquivos.Usuario;
import sistemacadastro.exceptions.ExceptionGravarArquivo;
import sistemacadastro.listener.ListenerTelaLogin;

/**
 *
 * @author Gregori
 */
public class TelaLogin extends javax.swing.JFrame {

    private ListenerTelaLogin listener = new ListenerTelaLogin(this);
    Usuario user = new Usuario();

    public Usuario setInfo() throws ExceptionGravarArquivo {
        user.setNome(login_jTextField.getText());
        user.setSenha(password_jPasswordField.getText());
        return user;
    }

    public void verificaLogin() {
        LerUsuario leitorAquivo;
        leitorAquivo = new LerUsuario();
        if (leitorAquivo.lerArquivo("login.txt") != null) {
            String[] info = leitorAquivo.lerArquivo("login.txt").split(";");
            user.setNome(info[0]);
            user.setSenha(info[1]);
            login_jTextField.setText(user.getNome());
            password_jPasswordField.setText(user.getSenha());
        } 
    }

    /**
     * Creates new form Login
     */
    public TelaLogin() {
        initComponents();
        verificaLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrar_jButton = new javax.swing.JButton();
        senha_jLabel = new javax.swing.JLabel();
        login_jLabel = new javax.swing.JLabel();
        login_jTextField = new javax.swing.JTextField();
        entrar_jLabel = new javax.swing.JLabel();
        password_jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        entrar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemacadastro/icones/accept.png"))); // NOI18N
        entrar_jButton.setText("Entrar");
        entrar_jButton.setActionCommand("Entrar");
        entrar_jButton.addActionListener(listener);
        entrar_jButton.setBorder(null);
        entrar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar_jButtonActionPerformed(evt);
            }
        });

        senha_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        senha_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        senha_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemacadastro/icones/key.png"))); // NOI18N
        senha_jLabel.setText("Senha");

        login_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        login_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemacadastro/icones/user.png"))); // NOI18N
        login_jLabel.setText("Login");

        login_jTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        entrar_jLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        entrar_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrar_jLabel.setText("Entrar");

        password_jPasswordField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        password_jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_jPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(senha_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(entrar_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrar_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(entrar_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(login_jLabel)
                    .addComponent(login_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(senha_jLabel)
                    .addComponent(password_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrar_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar_jButtonActionPerformed
        // TODO add your handling code here:
//        String login = login_jTextField.getText();
//        String password = evt.getActionCommand().copyValueOf(password_jPasswordField.getPassword());
// 
//        
//        if (login.equals(password)){
//            TelaPrincipal telaPrincipal = new TelaPrincipal();
//            telaPrincipal.setVisible(true);
//            setVisible(false);
//        } else {
//            JOptionPane.showMessageDialog(this, "Senha inválida para o usuario " + login, "Usuário ou senha inválidos",  JOptionPane.ERROR_MESSAGE);
//                }
//        
    }//GEN-LAST:event_entrar_jButtonActionPerformed

    private void password_jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar_jButton;
    private javax.swing.JLabel entrar_jLabel;
    private javax.swing.JLabel login_jLabel;
    private javax.swing.JTextField login_jTextField;
    private javax.swing.JPasswordField password_jPasswordField;
    private javax.swing.JLabel senha_jLabel;
    // End of variables declaration//GEN-END:variables

}
